version: 2

models:
  - name: dim_employee_scd2
    description: "Employee SCD2 dimension tracking historical changes"
    config:
      contract:
        enforced: true
    columns:
      - name: employee_id
        data_type: integer
        tests: [not_null]

      - name: valid_from
        data_type: timestamp
        tests: [not_null]

      - name: valid_to
        data_type: timestamp

      - name: is_current
        data_type: boolean
        tests: [not_null]

    tests:
      - unique:
          column_name: "(employee_id || '-' || valid_from)"

  - name: fct_hiring_funnel
    description: "Hiring funnel fact: one row per application per stage"
    config:
      contract:
        enforced: true
    columns:
      - name: application_id
        data_type: integer
        tests: [not_null]

      - name: stage
        data_type: string
        tests:
          - not_null
          - accepted_values:
              values: ['applied','screened','interviewed','offered','hired','rejected']

